const products = [
  {
    "company": "紅蘋果",
    "category": "裝飾櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR0020",
    "size": "500*395*1020",
    "height_type": null,
    "color": "ORI胡桃、親橡、橡木",
    "original_price_hkd": 1160,
    "salePrice": 986,
    "note": "鋁腳高度90mm，玻璃厚度8mm，鋁腳和鋁框顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR0025-40",
    "size": "1016*395*845",
    "height_type": "矮身",
    "color": "ORI胡桃、親橡、橡木",
    "original_price_hkd": 1850,
    "salePrice": 1573,
    "note": "鋁腳高度90mm，玻璃厚度8mm，鋁腳和鋁框顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR0025-48",
    "size": "1200*395*845",
    "height_type": "矮身",
    "color": "ORI胡桃、親橡、橡木",
    "original_price_hkd": 2280,
    "salePrice": 1938,
    "note": "鋁腳高度90mm，玻璃厚度8mm，鋁腳和鋁框顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR0025-60",
    "size": "1525*395*845",
    "height_type": "矮身",
    "color": "ORI胡桃、親橡、橡木",
    "original_price_hkd": 2670,
    "salePrice": 2270,
    "note": "鋁腳高度90mm，玻璃厚度8mm，鋁腳和鋁框顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR0045H-48",
    "size": "1194*400*2160",
    "height_type": "高身",
    "color": "白木紋",
    "original_price_hkd": 3850,
    "salePrice": 3273,
    "note": "鋁腳高度90mm，顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR010",
    "size": "428*400*980",
    "height_type": "矮身",
    "color": "白木紋",
    "original_price_hkd": 860,
    "salePrice": 731,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "餐邊櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR020",
    "size": "855*400*980",
    "height_type": "矮身",
    "color": "白木紋",
    "original_price_hkd": 1500,
    "salePrice": 1275,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "地櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR083-48",
    "size": "1200*395*595",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 1650,
    "salePrice": 1403,
    "note": "鋁腳高度90mm，鋁腳、鋁框和烤漆拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "地櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR083-60",
    "size": "1525*395*595",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 2280,
    "salePrice": 1938,
    "note": "鋁腳高度90mm，鋁腳、鋁框和烤漆拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "電視櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR083-60+TR083S-60",
    "size": "1525*395*2160",
    "height_type": null,
    "color": "白木紋",
    "original_price_hkd": 4900,
    "salePrice": 4165,
    "note": "可放42寸電視，鋁腳高度90mm，鋁腳、鋁框和烤漆拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "茶幾",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR186-32",
    "size": "800*500*435",
    "height_type": null,
    "color": "ORI胡桃、親橡",
    "original_price_hkd": 1250,
    "salePrice": 1063,
    "note": "臺面玻璃厚度12mm鋼化玻璃，鋁腳高度140mm，顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "桶櫃",
    "bucket_count": "四桶櫃",
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR504M",
    "size": "595*398*1005",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 1350,
    "salePrice": 1148,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "桶櫃",
    "bucket_count": "四桶櫃",
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR504L",
    "size": "800*460*1005",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 1700,
    "salePrice": 1445,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "桶櫃",
    "bucket_count": "五桶櫃",
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR505M",
    "size": "595*398*1158",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 1550,
    "salePrice": 1318,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "桶櫃",
    "bucket_count": "五桶櫃",
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR505L",
    "size": "800*460*1158",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 2080,
    "salePrice": 1768,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5312",
    "size": "770*350*1160",
    "height_type": "矮身",
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 1550,
    "salePrice": 1318,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5372",
    "size": "1200*320*1130",
    "height_type": "矮身",
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 2150,
    "salePrice": 1828,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5472",
    "size": "1195*320*1055",
    "height_type": "矮身",
    "color": "橡木",
    "original_price_hkd": 2080,
    "salePrice": 1768,
    "note": "拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5482",
    "size": "1200*395*1140",
    "height_type": "矮身",
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 2660,
    "salePrice": 2261,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5662",
    "size": "660*350*2160",
    "height_type": "高身",
    "color": "白木紋",
    "original_price_hkd": 2750,
    "salePrice": 2338,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5736-42",
    "size": "1066*380*2160",
    "height_type": "高身",
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 3880,
    "salePrice": 3298,
    "note": "",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5736-48",
    "size": "1200*380*2160",
    "height_type": "高身",
    "color": "ORI胡桃配白木紋、親橡、橡木",
    "original_price_hkd": 4350,
    "salePrice": 3698,
    "note": "",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "鞋櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR5802",
    "size": "800*320*1160",
    "height_type": "矮身",
    "color": "親橡、橡木",
    "original_price_hkd": 1500,
    "salePrice": 1275,
    "note": "鋁腳高度90mm，顏色為香檳金，拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "床頭櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR633-16",
    "size": "395*395*522",
    "height_type": null,
    "color": "橡木配白木紋",
    "original_price_hkd": 650,
    "salePrice": 553,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "床頭櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR633-20",
    "size": "500*395*522",
    "height_type": null,
    "color": "橡木配白木紋",
    "original_price_hkd": 700,
    "salePrice": 595,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "妝臺",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR6524+TRM36",
    "size": "595*395*760",
    "height_type": null,
    "color": "ORI胡桃、親橡",
    "original_price_hkd": 1100,
    "salePrice": 935,
    "note": "妝鏡為3mm银镜",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "無書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR720T-09",
    "size": "900*595*760",
    "height_type": null,
    "color": "ORI胡桃、親橡",
    "original_price_hkd": 1250,
    "salePrice": 1063,
    "note": "",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "無書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR730T-08",
    "size": "800*595*760",
    "height_type": null,
    "color": "白木紋",
    "original_price_hkd": 1680,
    "salePrice": 1428,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "無書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR730T-12",
    "size": "1200*595*760",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 1850,
    "salePrice": 1573,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "連書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR720T-09+TR730S-09",
    "size": "900*595*2160",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 3030,
    "salePrice": 2576,
    "note": "鋁腳高度90mm，鋁腳、鋁框和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "連書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR730T-08+TR730S-08",
    "size": "800*595*2160",
    "height_type": null,
    "color": "ORI胡桃、親橡",
    "original_price_hkd": 3050,
    "salePrice": 2593,
    "note": "鋁腳高度90mm，鋁腳、鋁框和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "連書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR730T-12+TR730S-12",
    "size": "1200*595*2160",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 3700,
    "salePrice": 3145,
    "note": "鋁腳高度90mm，鋁腳、鋁框和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書桌",
    "bucket_count": null,
    "with_bookshelf": "連書架",
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR710T+TR750S-06",
    "size": "660*590*2160",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 2100,
    "salePrice": 1780,
    "note": "鋁腳高度90mm，鋁腳、鋁框和拉手顏色為香檳金，金屬框為白色烤漆。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR732-04",
    "size": "400*295*2160",
    "height_type": null,
    "color": "親橡、橡木",
    "original_price_hkd": 1390,
    "salePrice": 1182,
    "note": "鋁框顏色為香檳金，門板不分左右。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR732-08",
    "size": "800*295*2160",
    "height_type": null,
    "color": "親橡、橡木",
    "original_price_hkd": 2290,
    "salePrice": 1947,
    "note": "鋁框顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR762-04",
    "size": "400*400*2160",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 1480,
    "salePrice": 1258,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金，門板不分左右。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "書櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR762-08",
    "size": "800*400*2160",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 2850,
    "salePrice": 2423,
    "note": "鋁腳高度90mm，鋁腳和拉手顏色為香檳金。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "碌架床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "SX362-36*72",
    "size": "979*1905*1780",
    "height_type": null,
    "color": "蔓綠+白木紋",
    "original_price_hkd": 6100,
    "salePrice": 5185,
    "note": "爬梯可選擇放左或右，爬梯和支柱為白色實木，護欄為金屬白色烤漆。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "無底床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR807H-B1-36*72",
    "size": "910*1904*992",
    "height_type": null,
    "color": "親橡",
    "original_price_hkd": 2530,
    "salePrice": 2151,
    "note": "床身高度為397mm，内空放置物高度可達325mm，U型金屬架為白色烤漆，鋁合金腳為香檳金。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "無底床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR807H-B1-48*72",
    "size": "1205*1904*992",
    "height_type": null,
    "color": "親橡",
    "original_price_hkd": 2950,
    "salePrice": 2508,
    "note": "床身高度為397mm，内空放置物高度可達325mm，U型金屬架為白色烤漆，鋁合金腳為香檳金。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "無底床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR807H-B1-54*75",
    "size": "1360*1974*992",
    "height_type": null,
    "color": "親橡",
    "original_price_hkd": 3230,
    "salePrice": 2746,
    "note": "床身高度為397mm，内空放置物高度可達325mm，U型金屬架為白色烤漆，鋁合金腳為香檳金。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-B-36*72",
    "size": "936*1894*1025",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 3150,
    "salePrice": 2678,
    "note": "床身高度為390mm，內空放置物高度可達329mm，附帶備用安全桿。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-B-48*72",
    "size": "1236*1894*1025",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 3770,
    "salePrice": 3205,
    "note": "床身高度為390mm，內空放置物高度可達329mm，附帶備用安全桿。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-B-54*75",
    "size": "1386*1969*1025",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 4160,
    "salePrice": 3536,
    "note": "床身高度為390mm，內空放置物高度可達329mm，附帶備用安全桿。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-B-60*75",
    "size": "1536*1969*1025",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 4450,
    "salePrice": 3783,
    "note": "床身高度為390mm，內空放置物高度可達329mm，附帶備用安全桿。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-P-36*72",
    "size": "936*1929*1025",
    "height_type": null,
    "color": "橡木",
    "original_price_hkd": 3600,
    "salePrice": 3060,
    "note": "床身高度為390mm，内空放置物高度可達329mm，床屏使用生態皮(卡其色)，附帶備用安全桿。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-P-48*72",
    "size": "1236*1929*1025",
    "height_type": null,
    "color": "橡木",
    "original_price_hkd": 4230,
    "salePrice": 3596,
    "note": "床身高度為390mm，内空放置物高度可達329mm，床屏使用生態皮(卡其色)，附帶備用安全桿。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-P-54*75",
    "size": "1386*2004*1025",
    "height_type": null,
    "color": "橡木",
    "original_price_hkd": 4650,
    "salePrice": 3953,
    "note": "床身高度為390mm，内空放置物高度可達329mm，床屏使用生態皮(卡其色)，附帶備用安全桿。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "油壓床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822-P-60*75",
    "size": "1536*2004*1025",
    "height_type": null,
    "color": "橡木",
    "original_price_hkd": 4750,
    "salePrice": 4038,
    "note": "床身高度為390mm，内空放置物高度可達329mm，床屏使用生態皮(卡其色)，附帶備用安全桿。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "高身油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822H-B-36*72",
    "size": "936*1894*1175",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 3490,
    "salePrice": 2967,
    "note": "床身高度為540mm，內空放置物高度可達479mm，附帶備用安全桿。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "高身油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822H-B-48*72",
    "size": "1236*1894*1175",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 4160,
    "salePrice": 3536,
    "note": "床身高度為540mm，內空放置物高度可達479mm，附帶備用安全桿。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "高身油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822H-B-54*75",
    "size": "1386*1969*1175",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 4580,
    "salePrice": 3893,
    "note": "床身高度為540mm，內空放置物高度可達479mm，附帶備用安全桿。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "高身油壓床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR822H-B-60*75",
    "size": "1536*1969*1175",
    "height_type": null,
    "color": "白木紋、親橡、橡木",
    "original_price_hkd": 4880,
    "salePrice": 4148,
    "note": "床身高度為540mm，內空放置物高度可達479mm，附帶備用安全桿。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-B-36*72",
    "size": "919*1878*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 2730,
    "salePrice": 2321,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-B-48*72",
    "size": "1219*1878*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋",
    "original_price_hkd": 3200,
    "salePrice": 2720,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-B-54*75",
    "size": "1376*1954*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3480,
    "salePrice": 2958,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-B-60*75",
    "size": "1524*1954*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3650,
    "salePrice": 3103,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-P-36*72",
    "size": "919*1866*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 2950,
    "salePrice": 2508,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-P-48*72",
    "size": "1219*1866*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3390,
    "salePrice": 2882,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-P-54*75",
    "size": "1376*1942*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋",
    "original_price_hkd": 3650,
    "salePrice": 3103,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": null,
    "door_type": null,
    "code": "TR839-P-60*75",
    "size": "1524*1942*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3850,
    "salePrice": 3273,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-B+TRG839-36",
    "size": "919*1878*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3180,
    "salePrice": 2703,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-B+TRG839-48",
    "size": "1219*1878*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋",
    "original_price_hkd": 3750,
    "salePrice": 3188,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-B+TRG839-54",
    "size": "1376*1954*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3950,
    "salePrice": 3358,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "無",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-B+TRG839-60",
    "size": "1524*1954*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 4150,
    "salePrice": 3528,
    "note": "床身高度為390mm，內空放置物高度可達349mm。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-P+TRG839-36",
    "size": "919*1866*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3400,
    "salePrice": 2890,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "三尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-P+TRG839-48",
    "size": "1219*1866*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 3900,
    "salePrice": 3315,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "四尺"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-P+TRG839-54",
    "size": "1376*1942*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋",
    "original_price_hkd": 4200,
    "salePrice": 3570,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "四尺半"
  },
  {
    "company": "紅蘋果",
    "category": "床",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": "三櫃桶床",
    "headboard_leather": "有",
    "with_tail_cabinet": "有",
    "door_type": null,
    "code": "TR839-P+TRG839-60",
    "size": "1524*1942*1025",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 4430,
    "salePrice": 3766,
    "note": "床身高度為390mm，內空放置物高度可達349mm，床屏使用生態皮(卡其色)。",
    "mattress_size_mm": "五尺"
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR921-08",
    "size": "800*600*2160",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 2680,
    "salePrice": 2278,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR921-12",
    "size": "1200*600*2160",
    "height_type": null,
    "color": "白木紋、橡木",
    "original_price_hkd": 3900,
    "salePrice": 3315,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR932-24",
    "size": "594*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 2550,
    "salePrice": 2168,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR932-35",
    "size": "890*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 3160,
    "salePrice": 2686,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR932-48",
    "size": "1191*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 4200,
    "salePrice": 3570,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR952-35",
    "size": "890*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 3760,
    "salePrice": 3196,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR9371-48",
    "size": "1191*600*2160",
    "height_type": null,
    "color": "白胡桃配卡其",
    "original_price_hkd": 5180,
    "salePrice": 4403,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "拉門",
    "code": "TR921-16",
    "size": "1500*600*2160",
    "height_type": null,
    "color": "ORI胡桃、親橡、白木紋、橡木",
    "original_price_hkd": 5988,
    "salePrice": 5090,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "TR952-48",
    "size": "1191*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡",
    "original_price_hkd": 4390,
    "salePrice": 3732,
    "note": "拉手顏色為銀色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "TR9219T-35",
    "size": "890*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、白木紋、橡木",
    "original_price_hkd": 3180,
    "salePrice": 2703,
    "note": "移門PVC封條顏色為淺咖色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "TR9219TG-48",
    "size": "1220*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、白木紋、橡木",
    "original_price_hkd": 4230,
    "salePrice": 3596,
    "note": "移門PVC封條顏色為淺咖色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "TR9219TG-60",
    "size": "1525*600*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋、親橡、白木紋、橡木",
    "original_price_hkd": 5090,
    "salePrice": 4327,
    "note": "移門PVC封條顏色為淺咖色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "T9216-12T",
    "size": "1210*597*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋",
    "original_price_hkd": 4350,
    "salePrice": 3698,
    "note": "可放置桶櫃(T9216G-12)，移門邊框為鋁合金槍灰色，拉手顏色為槍灰色。",
    "mattress_size_mm": null
  },
  {
    "company": "紅蘋果",
    "category": "衣櫃",
    "bucket_count": null,
    "with_bookshelf": null,
    "bed_type": null,
    "headboard_leather": null,
    "with_tail_cabinet": null,
    "door_type": "趟門",
    "code": "T9216-15T",
    "size": "1500*597*2160",
    "height_type": null,
    "color": "ORI胡桃配白木紋",
    "original_price_hkd": 4950,
    "salePrice": 4208,
    "note": "可放置桶櫃(T9216G-15)，移門邊框為鋁合金槍灰色，拉手顏色為槍灰色。",
    "mattress_size_mm": null
  }
];

export default products;
